[package]
name = "bbpipelinewait"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "2.34.0" }
reqwest = { version = "0.11.24", features = ["blocking", "json"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
directories = "5.0.1"
base64 = "0.21.7"
strum_macros = "0.26.1"
strum = "0.26.1"
log = "0.4.20"
url = "2.5.0"
