[package]
name = "bbpipelinewait"
version = "1.0.8"
description = "Tool to list running bitbucket pipelines and wait for them to stop."
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["cargo", "env"] }
reqwest = { version = "0.12.4", features = ["blocking", "json", "native-tls-vendored"] }
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
directories = "5.0.1"
base64 = "0.22.0"
strum_macros = "0.26.2"
strum = "0.26.2"
log = "0.4.21"
url = "2.5.0"
spinner = "0.5.0"
termsize = "0.1.6"
